import { useState, type FormEvent } from 'react';
import DOMPurify from 'dompurify';
import { useNavigate } from 'react-router-dom';

const rich = `<p><strong>Inertia</strong> is the tendency of an object to resist a change in its motion.</p><p>Think about a bus. When the bus suddenly starts, your body seems to move backward because your body wants to stay at rest. When the bus stops suddenly, your body moves forward because it wants to keep moving.</p><div class="callout"><strong>Remember:</strong> An object keeps its state of rest or uniform motion unless an external force changes it.</div>`;

export function Lesson() {
  const [font, setFont] = useState(1); const [simplify, setSimplify] = useState(false); const [speaking, setSpeaking] = useState(false); const [question, setQuestion] = useState(''); const [messages, setMessages] = useState([{from:'ai', text:'Of course. Think of inertia as an object’s resistance to change. A bus starting suddenly is a good example.'}]); const navigate = useNavigate();
  const speak = () => { if (!('speechSynthesis' in window)) return; speechSynthesis.cancel(); const u = new SpeechSynthesisUtterance(simplify ? 'Inertia means objects do not like changes in their motion.' : 'Inertia is the tendency of an object to resist a change in its motion.'); u.rate=.92; u.onend=()=>setSpeaking(false); setSpeaking(true); speechSynthesis.speak(u); };
  const ask = (e:FormEvent)=>{e.preventDefault(); if(!question.trim()) return; setMessages((m)=>[...m,{from:'user',text:question},{from:'ai',text:'Try this: imagine a cup on a table. It stays where it is until a push changes its motion. That resistance is inertia.'}]); setQuestion('');};
  return <div className="lesson-layout"><section className="lesson-main"><div className="breadcrumbs">Dashboard / Physics / <b>Laws of Motion</b></div><div className="lesson-scroll"><div className="lesson-content" style={{fontSize:`${font}em`}}><span className="eyebrow">PHYSICS • CHAPTER 4</span><h1>Newton's First Law of Motion</h1><div className="access-toolbar"><div><button onClick={speak}>🔊 {speaking?'Speaking…':'Read aloud'}</button><button onClick={()=>setSimplify(v=>!v)}>✦ {simplify?'Original language':'Simple mode'}</button><button onClick={()=>setFont(v=>v>=1.25?1:v+.1)}>T+ Text size</button></div><button className="btn primary" onClick={speak}>▶ {speaking?'Stop / replay':'Listen to lesson'}</button></div><div className="lesson-prose" dangerouslySetInnerHTML={{__html:DOMPurify.sanitize(rich,{ALLOWED_TAGS:['p','strong','div'],ALLOWED_ATTR:['class']})}}/><div className="concept-visual"><div className="bus">🚌</div><div className="person">🧍</div><span>Bus starts → body resists change</span></div><div className="lesson-actions"><button className="btn secondary" onClick={()=>navigate('/dashboard')}>← Back</button><button className="btn primary" onClick={()=>navigate('/dashboard')}>Mark complete ✓</button></div></div></div><div className="lesson-progress"><span>Page 12 of 18</span><div className="progress"><span style={{width:'65%'}}/></div><button>→</button></div></section><aside className="ai-panel"><div className="ai-header"><div className="ai-avatar">✦</div><div><b>Sahayak AI</b><span>● Online • English / Hindi</span></div></div><div className="chat-messages">{messages.map((m,i)=><div key={i} className={'message '+m.from}><span>{m.from==='ai'?'SAHAYAK AI':'YOU'}</span><p>{m.text}</p>{m.from==='ai'&&<button onClick={speak}>🔊 Listen</button>}</div>)}</div><form className="chat-form" onSubmit={ask}><input value={question} onChange={e=>setQuestion(e.target.value)} placeholder="Ask Sahayak anything…"/><button type="submit">↑</button></form><div className="suggestions"><button onClick={()=>setQuestion('Explain this in simple words')}>Simplify this</button><button onClick={()=>setQuestion('Give me a real-life example')}>Real-life example</button><button onClick={()=>setQuestion('Translate to Hindi')}>Translate to Hindi</button></div></aside></div>;
}
