import { useState } from 'react';
import { useForm, useWatch } from 'react-hook-form';
import { z } from 'zod';
import { zodResolver } from '@hookform/resolvers/zod';
import { useUpdateProfile } from '../features/api';
import { useAuth } from '../auth/AuthProvider';

const schema = z.object({ name:z.string().min(2), className:z.string().min(1), language:z.string().min(1), support:z.string().min(1) });
type FormData=z.infer<typeof schema>;
export function Profile(){ const { user } = useAuth(); const update=useUpdateProfile(); const [saved,setSaved]=useState(false); const {register,handleSubmit,control,formState:{errors}}=useForm<FormData>({resolver:zodResolver(schema),defaultValues:{name:user?.name ?? 'Arjun Kumar',className:user?.className ?? 'Class 10',language:'English + Hindi',support:'Audio-first'}}); const name=useWatch({control,name:'name'}) || ''; const displayName=name.trim() || 'Your name'; const avatar=displayName.charAt(0).toUpperCase(); const submit=async(d:FormData)=>{await update.mutateAsync(d);setSaved(true);setTimeout(()=>setSaved(false),2500)}; return <div><div className="page-heading"><div><span className="eyebrow">LEARNING PROFILE</span><h1>How can we help you learn better?</h1><p>These preferences personalize content and accessibility tools.</p></div>{saved&&<div className="toast">✓ Profile saved</div>}</div><form className="card profile-form" onSubmit={handleSubmit(submit)}><div className="profile-hero"><div className="avatar xlarge">{avatar}</div><div><h2>{displayName}</h2><span>Class 10 • Level 12</span></div></div><div className="form-grid"><label>Name<input {...register('name')}/>{errors.name&&<small className="field-error">{errors.name.message}</small>}</label><label>Class<input {...register('className')}/></label><label>Preferred language<select {...register('language')}><option>English + Hindi</option><option>Hindi</option><option>English</option><option>Marathi</option></select></label><label>Primary support<select {...register('support')}><option>Audio-first</option><option>Screen reader</option><option>Sign language</option><option>Simplified mode</option></select></label></div><div className="preference-grid"><div><b>Audio Lessons</b><span>Read lessons aloud and use narration.</span><button type="button" className="toggle on">On</button></div><div><b>Bigger Text</b><span>Increase reading size across lessons.</span><button type="button" className="toggle on">On</button></div><div><b>Simple Mode</b><span>Reduce visual and language complexity.</span><button type="button" className="toggle">Off</button></div></div><button className="btn primary" type="submit">Save learning profile</button></form></div> }
